### ISSUE TITLE
SSBench only creates containers then hangs

### ISSUE THREAD

**Issue by elligottmc** [swiftstack/ssbench#116]
Running ssbench with a very simple scenario is resulting in container creation but nothing else.

Output remains as below:

"INFO:Ensuring 1 containers (test02_*) exist; concurrency=10...
INFO:Initializing cluster with stock data (up to 1 concurrent workers)"

Containers are created but no file creations occur.
I have searched the web and openstack forums other have this issue but no answers, just one comment saying read the docs here (which I have).

Please advise.  Here's my scenario.  

{
  "name": "Small test scenario - Upload to 1 container",
  "sizes": [{
    "name": "tiny",
    "size_min": 4096,
    "size_max": 65536
  }, {
    "name": "small",
    "size_min": 100000,
    "size_max": 200000
  }],
  "initial_files": {
    "tiny": 10,
    "small": 10
  },
  "operation_count": 10,
  "crud_profile": [100, 0, 0, 0],
  "user_count": 1,
  "container_base": "test02",
  "container_count": 1,
  "container_concurrency": 10
}

**Comment by elligottmc** [comment]
Also should add that create, update delete of files works with swiftclient.

**Comment by clayg** [comment]
Are you running with `--keep-objects`?

**Comment by elligottmc** [comment]
No but I just tried.  Same result and again the job just appears to hang indefinitely (for days if I allow).

**Comment by timuralp** [comment]
@elligottmc you may have already resolved this or moved on from this issue, but if you're still stuck on this, could you paste the invocation command you were using?

**Comment by MaximBB** [comment]
I have the same issue on Fedora 23. Container is created and then nothing happens

./bin/ssbench-master -v run-scenario -f share/ssbench/scenarios/very_small.scenario -S "$STORAGE" -T $TOKEN -u 1 -c 1 -p Policy-0
2016-03-26 22:19:25,206:INFO:SwiftStack Benchmark (ssbench version 0.3.9)
2016-03-26 22:19:25,210:INFO:Starting scenario run for "Small test scenario"
2016-03-26 22:19:25,211:DEBUG:Using token fd2d4900b0284390bdfb6409b61a39bf at one of ['http://controller:8080/v1/AUTH_a1c551bbbf4f4affa940680daaab45c7']
2016-03-26 22:19:25,211:INFO:Ensuring 1 containers (ssbench_*) exist; concurrency=10...
2016-03-26 22:19:25,246:DEBUG:REQ: curl -i http://controller:8080/v1/AUTH_a1c551bbbf4f4affa940680daaab45c7/ssbench_000000_Policy-0 -I -H "X-Auth-Token: fd2d4900b0284390bdfb6409b61a39bf"
2016-03-26 22:19:25,246:DEBUG:RESP STATUS: 204
2016-03-26 22:19:25,246:INFO:Initializing cluster with stock data (up to 1 concurrent workers)
2016-03-26 22:19:25,247:DEBUG:active: 0 concurrency: 1

It gets stuck at
lib/python2.7/site-packages/ssbench/master.py
line 205
            self.work_push.send(msgpack.dumps(send_q))

When pyzmq is installed there is an error while building the package. Maybe it is somehow connected

    cc -c /tmp/timer_createN80gIj.c -o build/temp.linux-x86_64-2.7/tmp/timer_createN80gIj.o
    /tmp/timer_createN80gIj.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    /tmp/timer_createN80gIj.c: In function ‘main’:
    /tmp/timer_createN80gIj.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
         timer_create();
         ^
    cc build/temp.linux-x86_64-2.7/tmp/timer_createN80gIj.o -o build/temp.linux-x86_64-2.7/a.out
    build/temp.linux-x86_64-2.7/tmp/timer_createN80gIj.o: In function `main':
    timer_createN80gIj.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status

**Comment by timuralp** [comment]
@MaximBB can you also paste how the workers are started?

I'll try to reproduce this on a Fedora 23 VM.

**Comment by MaximBB** [comment]
There is actually issue with workers but I haven't investigated it further yet

[root@qtest ssbench-env]# ./bin/ssbench-master -v run-scenario -f share/ssbench/scenarios/very_small.scenario -S "$STORAGE" -T $TOKEN -u 1 -c 1 -p Policy-0 --workers 1
2016-03-26 23:24:25,972:INFO:SwiftStack Benchmark (ssbench version 0.3.8)
2016-03-26 23:24:25,974:INFO:Spawning local ssbench-worker (logging to /tmp/ssbench-worker-local-0.log) with ssbench-worker --zmq-host 127.0.0.1 --zmq-work-port 13579 --zmq-results-port 13580 --concurrency 1 --batch-size 1 -v 0
Traceback (most recent call last):
  File "./bin/ssbench-master", line 614, in <module>
    args.func(args)
  File "./bin/ssbench-master", line 217, in run_scenario
    close_fds=True))
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by timuralp** [comment]
@MaximBB thanks for the quick reply. If the worker doesn't start (as in the above output), the master will hang forever waiting for any worker to connect.

The most likely cause of the above error is related to finding the worker binary in the $PATH. You could work around this in one of two ways:
1. Start a separate worker process before starting the master:
```./bin/ssbench-worker --zmq-host localhost 1```
(or a different host for multi-node experiments; the "1" is a worker ID argument. It only needs to be unique between workers)
2. Add the path to the worker to $PATH:
```
PATH=<ssbench virtual env path>/bin:$PATH ./bin/ssbench-master -v run-scenario -f share/ssbench/scenarios/very_small.scenario -S "$STORAGE" -T $TOKEN -u 1 -c 1 -p Policy-0 --workers 1
```

Can you try either (or both) of these and report back? Also, I noticed that you're running this as root. That should not be required. If you run into issues using ssbench as a regular user, please report those as well.

**Comment by MaximBB** [comment]
@timuralp thanks a lot!
Both proposed options worked well!
It would be still useful if an error is raised if a worker process is not available. For new users even after reading available documentation it is not obvious

**Comment by timuralp** [comment]
@MaximBB glad that got resolved.

Good suggestion -- I will see what we could improve to make it more obvious that the master is waiting for a worker and a better error message when we cannot find the worker in the PATH.
