### ISSUE TITLE
CentOS 7 AttributeError: 'module' object has no attribute 'sslwrap'

### ISSUE THREAD

**Issue by HugoKuo** [swiftstack/ssbench#140]
```
(ssbench) [root@localhost benchmark]# ssbench-master run-scenario -f very_small.scenario -T AUTH_xxxxxxxxxxxxx -S https://cloud.swiftstack.com/v1/AUTH_hugo -u 2 -o 4 -c 1 --workers 2
INFO:SwiftStack Benchmark (ssbench version 0.3.9)
INFO:Spawning local ssbench-worker (logging to /tmp/ssbench-worker-local-0.log) with ssbench-worker --zmq-host 127.0.0.1 --zmq-work-port 13579 --zmq-results-port 13580 --concurrency 1 --batch-size 1 0
INFO:Spawning local ssbench-worker (logging to /tmp/ssbench-worker-local-1.log) with ssbench-worker --zmq-host 127.0.0.1 --zmq-work-port 13579 --zmq-results-port 13580 --concurrency 1 --batch-size 1 1
INFO:Starting scenario run for "Small test scenario"
INFO:Ensuring 1 containers (ssbench_*) exist; concurrency=10...
Traceback (most recent call last):
  File "/root/virtualenv/ssbench/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/root/virtualenv/ssbench/lib/python2.7/site-packages/ssbench/master.py", line 46, in _container_creator
    http_conn=http_conn)
  File "/root/virtualenv/ssbench/lib/python2.7/site-packages/ssbench/swift_client.py", line 549, in head_container
    conn.request(method, path, '', req_headers)
  File "/root/virtualenv/ssbench/lib/python2.7/site-packages/ssbench/swift_client.py", line 195, in request_escaped
    func(method, url, body=body, headers=headers or {})
  File "/usr/lib64/python2.7/httplib.py", line 1056, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1090, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1052, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 890, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 852, in send
    self.connect()
  File "/root/virtualenv/ssbench/lib/python2.7/site-packages/geventhttpclient/httplib.py", line 131, in connect
    sock, self.key_file, self.cert_file)
  File "/root/virtualenv/ssbench/lib/python2.7/site-packages/gevent/_ssl2.py", line 410, in wrap_socket
    ciphers=ciphers)
  File "/root/virtualenv/ssbench/lib/python2.7/site-packages/gevent/_ssl2.py", line 84, in __init__
    self._sslobj = _ssl.sslwrap(self._sock, server_side,
AttributeError: 'module' object has no attribute 'sslwrap'
<Greenlet at 0x7f5f16bef690: _container_creator(['https://cloud.swiftstack.com/v1/AUTH_hugo'], 'AUTH_xxxxxxxxxxxxxxxx', 'ssbench_000000_default_policy', policy=None)> failed with AttributeError

INFO:Initializing cluster with stock data (up to 2 concurrent workers)
```

**Comment by clayg** [comment]
Can you post which versions of python and gevent you are using - try to update gevent and see if that fixes it.
